services:
  carento-api:
    container_name: carento-api
    restart: always
    image: node:20.10.0
    ports:
      - 4005:3005
    volumes:
      - ./:/usr/src/carento
    working_dir: /usr/src/carento

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  carento-batch:
    container_name: carento-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4006:3006
    volumes:
      - ./:/usr/src/carento
    working_dir: /usr/src/carento

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# nestar-next:  localhost:4000 <=> container:3000
# nestar-api:   localhost:4001 <=> container:3007
# nestar-batch: localhost:4002 <=> container:3008
